Created the event model as well as corresponding tests and migrations.
RuItech/HiveMind pull request #11
Opened 2018-10-01 16:27 UTC by Argetan

As specified in #3 I have created the Event model which also validates that the `start_time` is before the `end_time`.

2018-10-02 07:21 UTC, jvdoorn commented
I'll have a look at why those tests failed later today and make an attempt to fix them.

2018-10-03 04:41 UTC, DavisRayM requested changes

2018-10-03 04:41 UTC, DavisRayM commented on hivemind/modules/api/tests/test_signals.py
> +    def test_event_clean(self):
Hey 😄 Thank you very much for the contribution first of all. Also, could you move this test into a TestCase of its own preferably the Event Model Tests as it doesn't truly fit in as a Signal. Other than that, thank you for contributing hope to see more Contributions 👍

2018-10-03 04:51 UTC, DavisRayM commented on hivemind/modules/api/models/event.py
> +
Please add a `created` and `modified` field. The `created` field will store the Data & Time at which the event is created while the `modified` field will store the last time the Event was modified.

2018-10-03 08:02 UTC, Argetan commented
If a lot of models are going to use `modified` and `created` fields we might want to create an abstract model that we can easily extend, see this [StackOverflow answer](https://stackoverflow.com/a/11031907/8150085) for more details on what I mean.

2018-10-03 08:09 UTC, DavisRayM commented
Seems like a good idea. Would you like to add it in this issue, by creating a ‘BaseModel’ class for now. Containing both the ‘created’ and ‘modifed’ fields

2018-10-03 08:10 UTC, Argetan commented
Sure thing, on it.

2018-10-03 08:41 UTC, DavisRayM commented on hivemind/modules/api/migrations/0004_auto_20181003_1015.py
> +
Not quite comfortable with having multiple Migrations for a new feature as it hasn't been implemented on any thing yet. How about we have one migration for this new model ?

2018-10-03 08:44 UTC, DavisRayM commented
Looks good to me so far. Will merge this into master after a bit. Just for the future though while making a PR from a fork please make sure that the branch you are working on within the fork isn't master.

2018-10-25 09:17 UTC, merged